USE [master]
GO

/****** Object:  Database [OrmDemoDB]    Script Date: 11/18/2013 11:39:32 ******/
CREATE DATABASE [OrmDemoDB] ON  PRIMARY 
( NAME = N'OrmDemoDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\OrmDemoDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OrmDemoDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\OrmDemoDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [OrmDemoDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OrmDemoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OrmDemoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OrmDemoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OrmDemoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OrmDemoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OrmDemoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [OrmDemoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OrmDemoDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [OrmDemoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OrmDemoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OrmDemoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OrmDemoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OrmDemoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OrmDemoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OrmDemoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OrmDemoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OrmDemoDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OrmDemoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OrmDemoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OrmDemoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OrmDemoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OrmDemoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OrmDemoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OrmDemoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OrmDemoDB] SET  READ_WRITE 
GO

ALTER DATABASE [OrmDemoDB] SET RECOVERY FULL 
GO

ALTER DATABASE [OrmDemoDB] SET  MULTI_USER 
GO

ALTER DATABASE [OrmDemoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OrmDemoDB] SET DB_CHAINING OFF 
GO


